steps:
  - name: "Docker Compose Test Python"
    command: python test.py
    plugins:
    - docker-compose#v3.1.0:
        run: app
  - wait
  - label: "Docker Build"
    commands:
      - "docker build -t andorpierdelacabeza/curso-buildkite:${BUILDKITE_COMMIT} --no-cache ."
      - "docker push andorpierdelacabeza/curso-buildkite:${BUILDKITE_COMMIT}"

  - label: ":rocket:"
    trigger: "proyecto-python-despliegue"
    if: build.branch == 'master'
    build:
      commit: "$BUILDKITE_COMMIT"
