steps:
  - name: "Docker Compose Test Python"
    command: python test.py
    plugins:
    - docker-compose#v3.1.0:
        run: app
  - wait
  - label: "Docker Build"
    commands:
      - "docker build -t andorpierdelacabeza/curso-buildkite:latest --no-cache ."
      - "docker tag andorpierdelacabeza/curso-buildkite:latest andorpierdelacabeza/curso-buildkite:${BUILDKITE_COMMIT}"
      - "docker push andorpierdelacabeza/curso-buildkite:latest"
      - "docker push andorpierdelacabeza/curso-buildkite:${BUILDKITE_COMMIT}"
