steps:
  - name: "Docker Compose Test Python"
    command: python test.py
    plugins:
    - docker-compose#v3.1.0:
        run: app
  - wait
  - label: "Docker Build"
    commands:
      - "docker build -t andorpierdelacabeza/curso-buildkite:${BUILDKITE_COMMIT} --no-cache ."
      - "docker push andorpierdelacabeza/curso-buildkite:${BUILDKITE_COMMIT}"
  - block: " ¿Listo para desplegar? :rocket: "
  - label: ":rocket: Despliega :kubernetes:"
    command: scripts/deploy.sh
    concurrency: 1
    concurrency_group: deploy/kubernetes
