apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: buildkite
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: andorpierdelacabeza/curso-buildkite:${BUILDKITE_COMMIT}
        ports:
        - containerPort: 8000
