apiVersion: "v1"
kind: "Service"
metadata:
  name: "python-deployment-service"
  namespace: "buildkite"
  labels:
    app: "python"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  selector:
    app: "python"
  type: "LoadBalancer"
  loadBalancerIP: ""
